In [17]:
import numpy as np

In [31]:
N = 3
A = np.array((-10, 10, 10))
T = np.array((2, 1, 3))
Q = 5
X = np.array((-15, -10, -5, 0, 5))


In [32]:
for i in range(N):
    print(i)
    if T[i] == 1:
        X += A[i]
    elif T[i] == 2:
        X[X<A[i]] = A[i]
        print(X)
    else:
        X[X>A[i]] = A[i]
    print(X)



0
[-10 -10  -5   0   5]
[-10 -10  -5   0   5]
1
[ 0  0  5 10 15]
2
[ 0  0  5 10 10]


In [5]:
def f(x, a, t):
    if t == 1:
        return x + a
    elif t == 2:
        return max(x, a)
    else:
        return min(x, a)

In [8]:
def fs(x):
    ans = x
    for i in range(N):
        ans = f(ans, a[i], t[i])
    return ans

In [11]:
fs(-5)

5

In [12]:
for xi in x:
    return fs(xi)

0
0
5
10
10
